Vagrant.configure("2") do |config| 
  config.vm.box = "spox/ubuntu-arm" 
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.synced_folder "/Users/nitinappiah/Desktop/DevOps/ubuntu/SharedDirectory",  "/home/vagrant/VagrantData"
  config.vm.provision "shell", inline: <<-SHELL
      echo "inside the shell script"
      sudo apt-get update
      sudo apt-get install -y apache2
    SHELL
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = false
    vmware.allowlist_verified = true
   end
 end
