Vagrant.configure("2") do |config|  
    # first server
    config.vm.define "apache_server" do |apache_server|
      apache_server.vm.box = "spox/ubuntu-arm" 
      apache_server.vm.box_version = "1.0.0"
      apache_server.vm.network "private_network", ip: "192.168.33.25"
      apache_server.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = false
        vmware.allowlist_verified = true
      end
      apache_server.vm.provision "shell", inline: <<-SHELL
          echo "inside the shell script"
          sudo apt update
          sudo apt install -y apache2 wget unzip
          cd /home/vagrant/
          wget https://www.tooplate.com/zip-templates/2129_crispy_kitchen.zip
          unzip -o ./2129_crispy_kitchen.zip
          sudo cp -r ./2129_crispy_kitchen/* /var/www/html/
      SHELL
      end
    # second server
    config.vm.define "wordpress_server" do |wordpress_server|
      wordpress_server.vm.box = "spox/ubuntu-arm"
      wordpress_server.vm.synced_folder "./SharedDirectory",  "/home/vagrant/VagrantData"
      wordpress_server.vm.network "private_network", ip: "192.168.33.17"
      wordpress_server.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = false
        vmware.allowlist_verified = true
      end
      wordpress_server.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install apache2 \
        ghostscript \
        libapache2-mod-php \
        mysql-server \
        php \
        php-bcmath \
        php-curl \
        php-imagick \
        php-intl \
        php-json \
        php-mbstring \
        php-mysql \
        php-xml \
        php-zip -y
      sudo mkdir -p /srv/www
      sudo chown www-data: /srv/www
      curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
      cp /home/vagrant/VagrantData/wordpress.conf /etc/apache2/sites-available/wordpress.conf
      sudo a2ensite wordpress
      sudo a2enmod rewrite
      sudo a2dissite 000-default
      sudo service apache2 reload
      sudo mysql -u root -e 'CREATE DATABASE wordpress;'
      sudo mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "AdMiN";'
      sudo mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
      sudo mysql -u root -e 'FLUSH PRIVILEGES;'
      sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
      sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
      sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
      sudo -u www-data sed -i 's/password_here/AdMiN/' /srv/www/wordpress/wp-config.php
      service mysql restart
      systemctl stop ufw  
    SHELL
    end
  end
  