# vagrant file to host a server
Vagrant.configure("2") do |config|
  config.vm.box = "spox/ubuntu-arm" 
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", ip: "192.168.56.25"
  config.vm.provision "shell", inline: <<-SHELL
      echo "inside the shell script"
      sudo apt-get update -y
      sudo apt-get install -y apache2 wget unzip
      cd /home/vagrant/
      wget https://www.tooplate.com/zip-templates/2129_crispy_kitchen.zip
      unzip ./2129_crispy_kitchen.zip
      sudo cp -r ./2129_crispy_kitchen/* /var/www/html/
    SHELL
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = false
    vmware.allowlist_verified = true
   end
 end
